# This config is public. Use .env for private and secure values.
# See https://www.npmjs.com/package/winston for custom console log formatting.
log:
  level: 'verbose' 
  format:
    info: 'bold blue'
    warn: 'bold yellow'
    error: 'bold red'
    debug: 'bold green'
    verbose: 'bold grey'
    silly: 'bold magenta'