version: '3.8'
services:  
  database:
    container_name: accord_database
    image: mongo:5-focal
    ports: [27017:27017]
    volumes: [accord:/data/db]
    restart: unless-stopped
  app:
    container_name: accord_app
    depends_on: [database]
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports: [3000:3000, 4200:4200]
    env_file: [./backend/.env, ./frontend/env/.env.dev]
    volumes:
      - ./backend/src:/app/backend/src
      - ./backend/assets:/app/backend/assets
      - ./backend/logs:/app/backend/logs
      - ./frontend/src:/app/frontend/src
    restart: unless-stopped
volumes:
  accord: